# Generated by Django 6.0 on 2026-02-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='miliege',
            new_name='Mileage',
        ),
    ]
