# Generated by Django 6.0 on 2026-02-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_rename_miliege_product_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
