# Generated by Django 6.0 on 2026-02-09 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/exterior/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exteriors', to='cbvapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/interior/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interiors', to='cbvapp.product')),
            ],
        ),
    ]
