# Generated by Django 6.0 on 2026-02-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0004_exterior_interior'),
        ('cbvapp', '0004_product_pro_img'),
    ]

    operations = [
    ]
