# Generated by Django 6.0 on 2026-02-10 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0005_merge_0004_exterior_interior_0004_product_pro_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
